package tn.esprit.pidev.entities.organization;

public enum ActivityType {
    ORGANIZATION_CREATED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_ACTIVATED,
    SUBSCRIPTION_CHANGED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    BUILDING_ADDED,
    BUILDING_REMOVED,
    LEASE_CREATED,
    LEASE_ACTIVATED,
    LEASE_TERMINATED,
    LEASE_EXPIRED,
    INSPECTION_CREATED,
    INSPECTION_COMPLETED,
    INSPECTION_DISPUTED
}
